version: "2.1"
services:
    blocky:
        image: spx01/blocky
        container_name: blocky
        restart: unless-stopped
        ports:
            - "953:953/tcp"
            - "953:953/udp"
            - "4000:4000/tcp"
        volumes:
            - ./config.yml:/app/config.yml
